services:
  grafana:
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-10.4.0}
    extra_hosts:
      - checkmk.local:host-gateway
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
