version: '3.0'

services:
  grafana:
    container_name: 'checkmk-cloud-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.4.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    extra_hosts:
      - checkmk.local:host-gateway
    volumes:
      - ./dist:/var/lib/grafana/plugins/checkmk-cloud-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/checkmk-cmkgrafanadatasource2-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.checkmk-cloud-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: checkmk-cloud-datasource

