version: '3.0'

services:
  grafana:
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.3.8}
    volumes:
      - ./dist:/var/lib/grafana/plugins/tribe-29-checkmk-datasource
      - ./provisioning:/etc/grafana/provisioning
    network_mode: host
  checkmk:
    image: checkmk/check-mk-free:2.1.0-latest
    volumes:
      - ./cypress/checkmk-docker-hooks:/docker-entrypoint.d
    network_mode: host
