name: Run the e2e tests
on: push
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run the e2e tests
        run: docker-compose up --exit-code-from=cypress
        working-directory: tests/
